[package]
name = "shared-vec"
version = "0.1.0"
edition = "2021"
rust-version = "1.87.0"
description = "Efficient shared container types"
repository = "https://github.com/TheVeryDarkness/shared-vec.git"
license = "MIT OR Apache-2.0"
categories = ["data-structures", "no-std"]

[features]
serde = ["dep:serde"]
schemars = ["dep:schemars"]

[dependencies]
serde = { version = "1.0.228", optional = true, default-features = false, features = [
    "alloc",
] }
schemars = { version = "1.1.0", optional = true, default-features = false }

[dev-dependencies]
itertools = "0.14.0"
serde_json = { version = "1.0.145", default-features = false, features = [
    "alloc",
] }

[lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
unreachable_pub = "warn"

[lints.rustdoc]
invalid_html_tags = "warn"
missing_crate_level_docs = "warn"
