edition = "2024"
error_on_line_overflow = true
error_on_unformatted = true
format_macro_matchers = true
group_imports = "One"
imports_granularity = "Module"
reorder_impl_items = true
unstable_features = true
